name: currency-exchange

services:
  postgres:
    image: postgres:16-alpine
    container_name: currency_db
    environment:
      POSTGRES_DB: currency_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 90029002
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - currency-network

  migrator:
    build:
      context: .
      dockerfile: deployment/Dockerfile
      args:
        SERVICE_DIR: currency-service
        BUILD_TARGET: ./cmd/migrator/main.go
        BINARY_NAME: migrator
    image: currency-migrator:latest
    container_name: currency-migrator
    environment:
      DATABASE_URL: postgres://postgres:90029002@postgres:5432/currency_db?sslmode=disable
      DATABASE_DRIVER: "postgres"
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"
    networks:
      - currency-network

  currency-api:
    build:
      context: .
      dockerfile: deployment/Dockerfile
      args:
        SERVICE_DIR: currency-service
        BUILD_TARGET: ./cmd/api/main.go
        BINARY_NAME: currency-api
    image: currency-api:latest
    container_name: currency_api
    ports:
      - "8082:8082"
    environment:
      PORT: 8082
      EXCHANGE_API_KEY: 9c6542ec9e89a700eaaf6a4d
      BASE_CURRENCY: RUB
      DATABASE_URL: postgres://postgres:90029002@postgres:5432/currency_db?sslmode=disable
      DATABASE_DRIVER: postgres
      CURRENCY_API_URL: https://api.exchangerate-api.com/v4
      ENVIRONMENT: production
    depends_on:
      postgres:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    restart: unless-stopped
    networks:
      - currency-network

  currency-worker:
    build:
      context: .
      dockerfile: deployment/Dockerfile
      args:
        SERVICE_DIR: currency-service
        BUILD_TARGET: ./cmd/worker/main.go
        BINARY_NAME: currency-worker
    image: currency-worker:latest
    container_name: currency_worker
    environment:
      CURRENCY_API_URL: https://api.exchangerate-api.com/v4
      EXCHANGE_API_KEY: 9c6542ec9e89a700eaaf6a4d
      BASE_CURRENCY: RUB
      DATABASE_URL: postgres://postgres:90029002@postgres:5432/currency_db?sslmode=disable
      DATABASE_DRIVER: postgres
      ENVIRONMENT: production
    depends_on:
      postgres:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    restart: unless-stopped
    networks:
      - currency-network

  auth-service:
    build:
      context: .
      dockerfile: deployment/Dockerfile
      args:
        SERVICE_DIR: auth-service
        BUILD_TARGET: ./main.go
        BINARY_NAME: auth-service
    image: auth-service:latest
    container_name: auth_service
    ports:
      - "8081:8081"
    environment:
      JWT_SECRET: my-production-secret-key-12345
    restart: unless-stopped
    networks:
      - currency-network

  gateway:
    build:
      context: .
      dockerfile: deployment/Dockerfile
      args:
        SERVICE_DIR: gateway
        BUILD_TARGET: ./cmd/gateway/main.go
        BINARY_NAME: gateway
    image: gateway:latest
    container_name: gateway
    ports:
      - "8380:8080"
    environment:
      PORT: 8080
      CURRENCY_API_URL: http://currency-api:8082
      AUTH_API_URL: http://auth-service:8081
      JWT_SECRET: my-production-secret-key-12345
      ENVIRONMENT: production
    depends_on:
      - auth-service
      - currency-api
    restart: unless-stopped
    networks:
      - currency-network

volumes:
  postgres_data:
    driver: local

networks:
  currency-network:
    driver: bridge
