// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: currency/currency.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetRateRequest запрос курса валюты
type GetRateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          string                 `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`     // Базовая валюта (например: USD, RUB)
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"` // Целевая валюта (например: EUR, JPY)
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`     // Дата в формате YYYY-MM-DD
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRateRequest) Reset() {
	*x = GetRateRequest{}
	mi := &file_currency_currency_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateRequest) ProtoMessage() {}

func (x *GetRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_currency_currency_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateRequest.ProtoReflect.Descriptor instead.
func (*GetRateRequest) Descriptor() ([]byte, []int) {
	return file_currency_currency_proto_rawDescGZIP(), []int{0}
}

func (x *GetRateRequest) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *GetRateRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *GetRateRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

// GetRateResponse ответ с курсом валюты
type GetRateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          string                 `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Rate          float64                `protobuf:"fixed64,3,opt,name=rate,proto3" json:"rate,omitempty"`
	Date          string                 `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"` // Опциональная ошибка
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRateResponse) Reset() {
	*x = GetRateResponse{}
	mi := &file_currency_currency_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateResponse) ProtoMessage() {}

func (x *GetRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_currency_currency_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateResponse.ProtoReflect.Descriptor instead.
func (*GetRateResponse) Descriptor() ([]byte, []int) {
	return file_currency_currency_proto_rawDescGZIP(), []int{1}
}

func (x *GetRateResponse) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *GetRateResponse) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *GetRateResponse) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *GetRateResponse) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetRateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetHistoryRequest запрос истории курсов
type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          string                 `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	StartDate     string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_currency_currency_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_currency_currency_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_currency_currency_proto_rawDescGZIP(), []int{2}
}

func (x *GetHistoryRequest) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *GetHistoryRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *GetHistoryRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetHistoryRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

// GetHistoryResponse ответ с историческими данными
type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          string                 `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Data          []*ExchangeRate        `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_currency_currency_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_currency_currency_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_currency_currency_proto_rawDescGZIP(), []int{3}
}

func (x *GetHistoryResponse) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *GetHistoryResponse) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *GetHistoryResponse) GetData() []*ExchangeRate {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetHistoryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ExchangeRate представляет курс валюты
type ExchangeRate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Base          string                 `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Rate          float64                `protobuf:"fixed64,4,opt,name=rate,proto3" json:"rate,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRate) Reset() {
	*x = ExchangeRate{}
	mi := &file_currency_currency_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRate) ProtoMessage() {}

func (x *ExchangeRate) ProtoReflect() protoreflect.Message {
	mi := &file_currency_currency_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRate.ProtoReflect.Descriptor instead.
func (*ExchangeRate) Descriptor() ([]byte, []int) {
	return file_currency_currency_proto_rawDescGZIP(), []int{4}
}

func (x *ExchangeRate) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExchangeRate) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *ExchangeRate) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ExchangeRate) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *ExchangeRate) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *ExchangeRate) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ExchangeRate) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// HealthCheckRequest запрос проверки здоровья сервиса
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_currency_currency_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_currency_currency_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_currency_currency_proto_rawDescGZIP(), []int{5}
}

// HealthCheckResponse ответ о состоянии сервиса
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Time          string                 `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_currency_currency_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_currency_currency_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_currency_currency_proto_rawDescGZIP(), []int{6}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

var File_currency_currency_proto protoreflect.FileDescriptor

const file_currency_currency_proto_rawDesc = "" +
	"\n" +
	"\x17currency/currency.proto\x12\bcurrency\x1a\x1fgoogle/protobuf/timestamp.proto\"P\n" +
	"\x0eGetRateRequest\x12\x12\n" +
	"\x04base\x18\x01 \x01(\tR\x04base\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\"{\n" +
	"\x0fGetRateResponse\x12\x12\n" +
	"\x04base\x18\x01 \x01(\tR\x04base\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x12\n" +
	"\x04rate\x18\x03 \x01(\x01R\x04rate\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"y\n" +
	"\x11GetHistoryRequest\x12\x12\n" +
	"\x04base\x18\x01 \x01(\tR\x04base\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\"\x82\x01\n" +
	"\x12GetHistoryResponse\x12\x12\n" +
	"\x04base\x18\x01 \x01(\tR\x04base\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12*\n" +
	"\x04data\x18\x03 \x03(\v2\x16.currency.ExchangeRateR\x04data\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x84\x02\n" +
	"\fExchangeRate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04base\x18\x02 \x01(\tR\x04base\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x12\n" +
	"\x04rate\x18\x04 \x01(\x01R\x04rate\x12.\n" +
	"\x04date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x14\n" +
	"\x12HealthCheckRequest\"A\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04time\x18\x02 \x01(\tR\x04time2\xe6\x01\n" +
	"\x0fCurrencyService\x12>\n" +
	"\aGetRate\x12\x18.currency.GetRateRequest\x1a\x19.currency.GetRateResponse\x12G\n" +
	"\n" +
	"GetHistory\x12\x1b.currency.GetHistoryRequest\x1a\x1c.currency.GetHistoryResponse\x12J\n" +
	"\vHealthCheck\x12\x1c.currency.HealthCheckRequest\x1a\x1d.currency.HealthCheckResponseB'Z%github.com/alfascuf/PROD1/pkg/grpc/pbb\x06proto3"

var (
	file_currency_currency_proto_rawDescOnce sync.Once
	file_currency_currency_proto_rawDescData []byte
)

func file_currency_currency_proto_rawDescGZIP() []byte {
	file_currency_currency_proto_rawDescOnce.Do(func() {
		file_currency_currency_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_currency_currency_proto_rawDesc), len(file_currency_currency_proto_rawDesc)))
	})
	return file_currency_currency_proto_rawDescData
}

var file_currency_currency_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_currency_currency_proto_goTypes = []any{
	(*GetRateRequest)(nil),        // 0: currency.GetRateRequest
	(*GetRateResponse)(nil),       // 1: currency.GetRateResponse
	(*GetHistoryRequest)(nil),     // 2: currency.GetHistoryRequest
	(*GetHistoryResponse)(nil),    // 3: currency.GetHistoryResponse
	(*ExchangeRate)(nil),          // 4: currency.ExchangeRate
	(*HealthCheckRequest)(nil),    // 5: currency.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 6: currency.HealthCheckResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_currency_currency_proto_depIdxs = []int32{
	4, // 0: currency.GetHistoryResponse.data:type_name -> currency.ExchangeRate
	7, // 1: currency.ExchangeRate.date:type_name -> google.protobuf.Timestamp
	7, // 2: currency.ExchangeRate.created_at:type_name -> google.protobuf.Timestamp
	7, // 3: currency.ExchangeRate.updated_at:type_name -> google.protobuf.Timestamp
	0, // 4: currency.CurrencyService.GetRate:input_type -> currency.GetRateRequest
	2, // 5: currency.CurrencyService.GetHistory:input_type -> currency.GetHistoryRequest
	5, // 6: currency.CurrencyService.HealthCheck:input_type -> currency.HealthCheckRequest
	1, // 7: currency.CurrencyService.GetRate:output_type -> currency.GetRateResponse
	3, // 8: currency.CurrencyService.GetHistory:output_type -> currency.GetHistoryResponse
	6, // 9: currency.CurrencyService.HealthCheck:output_type -> currency.HealthCheckResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_currency_currency_proto_init() }
func file_currency_currency_proto_init() {
	if File_currency_currency_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_currency_currency_proto_rawDesc), len(file_currency_currency_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_currency_currency_proto_goTypes,
		DependencyIndexes: file_currency_currency_proto_depIdxs,
		MessageInfos:      file_currency_currency_proto_msgTypes,
	}.Build()
	File_currency_currency_proto = out.File
	file_currency_currency_proto_goTypes = nil
	file_currency_currency_proto_depIdxs = nil
}
